"""Stage 9: cold-path investigation narratives for flagged transactions.

The LLM sits on the COLD PATH only: it drafts investigation summaries for
human analysts after a deterministic, auditable model has made the real-time
authorization decision. It never scores transactions.

Two generators:
  * template  -- deterministic, dependency-free; always available (fallback);
  * anthropic -- calls the Anthropic Messages API (claude-sonnet-4-6) via
                 plain HTTPS when ANTHROPIC_API_KEY is set. Outputs cached.
"""
from __future__ import annotations

import json
import os

FEATURE_GLOSS = {
    "amt_log": "transaction amount (log scale)",
    "amt_cents": "non-integer cents pattern in the amount",
    "TransactionAmt": "transaction amount",
    "hour": "hour of day",
    "dow": "day of week",
    "card1_past_count": "number of prior transactions from this card profile",
    "card1_since_last": "time since this card profile's previous transaction",
    "card1_past_amt_mean": "card profile's historical average amount",
    "card1_amt_ratio": "amount relative to the card profile's history",
    "card1_addr1_past_count": "prior transactions from this card+address pair",
    "card1_addr1_since_last": "time since last card+address transaction",
    "card1_addr1_past_amt_mean": "card+address historical average amount",
    "card1_addr1_amt_ratio": "amount vs card+address history",
    "P_emaildomain": "purchaser email domain",
    "R_emaildomain": "recipient email domain",
    "DeviceType": "device type",
    "DeviceInfo": "device fingerprint",
    "ProductCD": "product code",
    "dist1": "billing-to-purchaser distance",
    "dist2": "secondary address distance",
    "addr1": "billing region code",
    "has_identity": "identity information present",
}


def _gloss(feature: str) -> str:
    if feature in FEATURE_GLOSS:
        return FEATURE_GLOSS[feature]
    if feature.startswith("C"):
        return f"count feature {feature} (e.g. cards/addresses associated)"
    if feature.startswith("D"):
        return f"time-delta feature {feature} (days since a prior event)"
    if feature.startswith("V"):
        return f"Vesta engineered signal {feature}"
    if feature.startswith("M"):
        return f"identity-match flag {feature}"
    if feature.startswith("id_"):
        return f"identity attribute {feature}"
    return feature


def template_narrative(txn: dict, contribs: list[dict], threshold: float) -> str:
    """Deterministic analyst-style summary from structured inputs.

    txn: {TransactionID, amt, p_cal, ProductCD, hour, ...}
    contribs: [{feature, value, shap}], sorted by |shap| desc (top risk first)
    """
    risk = [c for c in contribs if c["shap"] > 0][:4]
    mitig = [c for c in contribs if c["shap"] < 0][:2]

    lines = [
        f"Transaction {txn['TransactionID']} for ${txn['amt']:,.2f} "
        f"(product {txn.get('ProductCD', '?')}, hour {txn.get('hour', '?')}) "
        f"received a calibrated fraud probability of {txn['p_cal']:.1%}, above "
        f"the cost-optimal decline threshold of {threshold:.1%}."
    ]
    if risk:
        lines.append("Primary risk drivers: " + "; ".join(
            f"{_gloss(c['feature'])} ({c['feature']}={_fmt(c['value'])}, "
            f"+{c['shap']:.2f} log-odds)" for c in risk) + ".")
    if mitig:
        lines.append("Partially offsetting signals: " + "; ".join(
            f"{_gloss(c['feature'])} ({_fmt(c['value'])}, {c['shap']:.2f})"
            for c in mitig) + ".")
    lines.append(
        "Suggested next steps: verify cardholder contact and recent history for "
        "this card profile; if confirmed legitimate, whitelist and route future "
        "transactions of this profile to step-up authentication instead of decline.")
    lines.append("[Generated by deterministic template - LLM cold-path "
                 "narrative unavailable without ANTHROPIC_API_KEY.]")
    return "\n".join(lines)


def _fmt(v) -> str:
    if v is None:
        return "missing"
    if isinstance(v, float):
        return "missing" if v != v else f"{v:,.2f}"
    return str(v)


ANTHROPIC_MODEL = "claude-sonnet-4-6"
SYSTEM_PROMPT = (
    "You are a fraud-operations analyst assistant. Given structured facts about "
    "a card-not-present transaction that a calibrated model declined, write a "
    "4-6 sentence investigation note: what drove the score, what would confirm "
    "or clear the alert, and a next step. Use only the provided facts; do not "
    "invent details. Plain prose, no markdown.")


def llm_narrative(txn: dict, contribs: list[dict], threshold: float,
                  timeout: int = 30) -> str | None:
    """Anthropic Messages API via plain HTTPS. Returns None when unavailable."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return None
    import requests  # local import: optional dependency path
    facts = {"transaction": txn, "top_shap_contributions": contribs,
             "decline_threshold": threshold}
    try:
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers={"x-api-key": api_key,
                     "anthropic-version": "2023-06-01",
                     "content-type": "application/json"},
            json={"model": ANTHROPIC_MODEL, "max_tokens": 400,
                  "system": SYSTEM_PROMPT,
                  "messages": [{"role": "user",
                                "content": json.dumps(facts, default=str)}]},
            timeout=timeout)
        resp.raise_for_status()
        return resp.json()["content"][0]["text"]
    except Exception:
        return None


def narrative(txn: dict, contribs: list[dict], threshold: float) -> dict:
    text = llm_narrative(txn, contribs, threshold)
    source = "anthropic" if text else "template"
    if text is None:
        text = template_narrative(txn, contribs, threshold)
    return {"TransactionID": txn["TransactionID"], "source": source,
            "text": text}
